### ISSUE TITLE
k-way anova door recoding factors??

### ISSUE THREAD

**Issue by rebeccakuiper** [cjvanlissa/gorica#13]
Gaat opmerking in Bain tutorial ook voor ons op??
Ik hoop het niet...

opmerking in Bain tutorial:
Two-way or higher order ANOVA's can only be handled by recoding all factors into one factor. If, or example, there is a factor `sex` with levels `man` and `woman`, and a factor `age` with levels `young` and `old`, these have to be recoded in a new factor `sexage` with levels `manyoung`, `manold`, `womanyoung`, `womanold`

**Comment by cjvanlissa** [comment]
Nee, dit is omdat Bain de analyse opnieuw draait, en Gorica niet. Gorica heeft op dat gebied veel meer vrijheid.
