### ISSUE TITLE
Net als bij bain ook een ttest object als input mogelijk? Of alleen (g)lm()?

### ISSUE THREAD

**Issue by rebeccakuiper** [cjvanlissa/gorica#14]

**Comment by cjvanlissa** [comment]
Ik heb de ttest er nu uitgesloopt; de reden is dat de standaard t-test geen varianties of ruwe data teruggeeft, waardoor je een nieuwe ttest functie moet maken. Dus je moet gebruikers uitleggen dat ze voortaan t_test moeten gebruiken in plaats van t.test. Het is dan net zo makkelijk om dat achterwege te laten, en mensen te vertellen dat ze hun t.test met aov() of lm() moeten runnen. Die verwerkt gorica() prima.
