### ISSUE TITLE
Output: relative weigth (zie comment)

### ISSUE THREAD

**Issue by rebeccakuiper** [cjvanlissa/gorica#23]
Ook een matrix maken (van relative weights) zoals bain met BFmatrix. 
Dat evt alleen opvraagbaar, maar mag ook standaard output zijn.

Evt mbt "Ik wil bijv, als lik = max lik is, aangeven wat max relative weight is of zeggen dat er nu een max is tov hypo’s met zelfde lik.":
Dan in rel weight matrix aangeven welke hun max hebben (nl als gelijke LL, dus ook als twee gelijk hebben maar ll niet max is).

**Comment by rebeccakuiper** [comment]
my_gorica <- gorica(fit.lm, HypoSet)

STEL weights opvraagbaar met "my_gorica$gorica_weights". Dan:

# relative weight H2 vs H1
my_gorica$gorica_weights[2] / my_gorica$gorica_weights[1]

Ik zou dat voor alle hypotheses willen (als een set van hypotheses), zoals ook BFmatrix in bain.

NB Als complement & meerdere hypotheses (kan nu nog niet) dan alleen weights tov eigen complement en niet ook zo'n rel.weights.matrix ovs die weights.

**Comment by rebeccakuiper** [comment]
Dit was gelijk aan #7 (die sluit ik dan).

Comment daar:
Laten we ook rel weights zien (ook tov complement)? Ws niet, ms ook een mx maken zoals bain met BF. Dan daar aangeven welke hun max hebben (nl als gelijke LL, dus ook als twee gelijk hebben maar LL niet max is).

**Comment by cjvanlissa** [comment]
Is de berekening correct?

loglik %*% t(1/loglik) / penalty %*% t(1/penalty)

**Comment by rebeccakuiper** [comment]
Ik zou zeggen dat je er met nu al berekende gorica weights er het snelst komt... dus dan heb je loglik en penalty niet meer nodig.

gorica.weights %*% t(1/gorica.weights)

**Comment by rebeccakuiper** [comment]
Nb Dan heb je de relative weight van H_{rij} versus H_{column}.
Wellicht is het handig om dan bij de rijen gewoon de H_m's te noemen en dan bij de kolommen niet de H_m's maar "versus H_m"'s, las je snapt wat ik bedoel... Dus de output ziet er dan bijv zo uit:
      vs H1   vs H2   vs Hu
H1        1     0.333   0.167
H2        3           1    0.500
Hu        6           2          1
