### ISSUE TITLE
Test against complement of hypotheses

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/gorica#3]
Also incorporate the functionality of evaluating a hypothesis against its complement (and if more than one substantive hypothesis: also the complement of the set).

**Comment by cjvanlissa** [comment]
Rebecca: Include output voor evaluatie van een hypothese tegen zijn complement:
5) Doe jij dat obv code in restriktor package van Leonard?

**Comment by rebeccakuiper** [comment]
Ik heb je code gestuurd.
Wellicht kan je dat al implementeren en anders kijken we er samen naar.

Dan naar restriktor verwijzen en/of (nu nog unplished) artikel van Leonard en mij.
Leonard ook co-auteur op gorica.

**Comment by rebeccakuiper** [comment]
Noem het ook complement = T or F
Dan zelfde als in restriktor. 

Nb over tijdje bij set van hypo's ook complement van set info hypo mogelijk

**Comment by cjvanlissa** [comment]
Is dat verstandig? Als je de complement opvraagt, dan is de "unconstrained" hypothese niet meer mogelijk, toch? Als deze twee opties elkaar uitsluiten, dan is het logischer om één argument met twee opties te maken, in plaats van twee losse argumenten die niet onafhankelijk zijn.

**Comment by rebeccakuiper** [comment]
Klopt. 

Het idee is dan dat het by default complement = F is (dus met unconstrained) en je alleen complement = T hoeft op te geven (dan krijg je complement en niet unconstrained). Kortom, er is maar 1 argument (niet twee).

Waar mij het om gaat is dat de beide functies niet te erg uiteenlopen want dat is heet irritant in cursussen (straks) en handleidingen... kortom, in gebruik :-).

Ik kan ook Leonard vragen of hij het wil aanpassen...

Ik kan alleen geen goede naam verzinnen voor een argument dan... Wellicht 'safeguard' of 'alternative'.
Maar dan moet je dus de namen uitschrijven... of gaat het dan met de eerste letters (dus u en c) ook goed?

**Comment by cjvanlissa** [comment]
Ja, ik had nu een argument comparison = "", dat standaard op "unconstrained" staat, en ook de waarden "complement" en "none" kan hebben. Het werkt met partial matching, dus comparison = "un" werkt evengoed als "unconstrained".

**Comment by rebeccakuiper** [comment]
Door dat partial matching is het zeker ook gebruiksvriendelijk.

Ik heb dit aan Leonard voorgelegd.
