### ISSUE TITLE
Fout in bepalen PT van compl 

### ISSUE THREAD

**Issue by rebeccakuiper** [cjvanlissa/gorica#30]
Bijgevoegd een file waar je kan zien dat het fout gaat: Ik zal het e-mailen, want ik krijg melding dat deze type file niet gesupport wordt...

Ik krijg zelfs een negatieve penalty voor het complement (en het zou iets dicht bij 12 moeten zijn, iig tussen 0 en 12)...
Ik heb ik restriktor geprobeerd met soortgelijke hypo en dan in een regressie model en daar gaat penalty bepalen voor het complement wel goed; dus ik denk dat het ergens in jouw code zit.... Wellicht moet je code van restriktor aanroepen??

**Comment by rebeccakuiper** [comment]
Er moet trouwens nog een aanpassing gedaan worden, ws ook als je de complement code van Leonard gaat aanroepen of overnemen:
Bij de gorica, als de de complement code gebruikt, moet van de penalty nog 1 af.

Als je een hypothese H1 met alleen ='en neemt, dan moet de PT bepaalt voor H1 vs Hu en ook voor H1 vs Hcompl, dan zou dat beide hetzelfde moeten geven.
[Nu is PT voor compl dus 1 te hoog]

**Comment by rebeccakuiper** [comment]
Ik weet dat we vrijdag hebben afgesproken, maar ik denk niet dat we dan direct dit oplossen... Ik denk dat het daarom verstandig is om deze code eerst de disable'n. De code is nu echt fout en het zou jammer zijn als mensen hier gebruik van gaan maken...

**Comment by cjvanlissa** [comment]
#2223cf850fb922b051b30f36bc7158b3177c331a
